# Generated by Django 3.0.3 on 2020-07-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='num_of_favorites',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
